version: '3.8'

services:
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask-blog-app
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - flask_data:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Alternative service using Alpine Linux (uncomment if main service fails)
  # flask-app-alpine:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.alpine
  #   container_name: flask-blog-app-alpine
  #   ports:
  #     - "8081:5000"
  #   environment:
  #     - FLASK_ENV=production
  #     - PORT=5000
  #   volumes:
  #     - flask_data:/app/instance
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5000/"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

volumes:
  flask_data:
    driver: local 